### ISSUE TITLE
Problem with ok_dial_box: Couldn't find a component factory for 'Invention'

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#125] opened 2024-04-10 18:05 UTC
version 2.10.1

- starts a new game, builds a monument, then use maximum speed
- a popup appears with an error like `Problem with ok_dial_box: 'cricketup.mes' + ""`

Also, on stdout:
`Problem with ok_dial_box: Couldn't find a component factory for 'Invention'`

**Comment by dbear496** [comment] 2024-04-11 18:52
This is probably a duplicate of #122

**Closed** 2024-04-12 16:10 UTC
Labels: duplicate
