### ISSUE TITLE
Sometimes percentages are over 100%

### ISSUE THREAD

**Issue by FabioPedretti** [lincity-ng/lincity-ng#150] opened 2024-07-07 13:12 UTC
Version: 2.11.0

I noticed that sometime production percentages get over 100% (I even see over 400%). Also all the percentages of the building are the same (see the screenshot). If I save the game and then reload it, the percentages are <= 100% and they are different again, so it may be a temporary or a visualization issue.

![over100](https://github.com/lincity-ng/lincity-ng/assets/3390837/a7a45c97-6ea1-4172-b52d-1fbf0f7bc36a)

I am anyway attaching a savegame where the percentage of blacksmith 10 was 118%.
[2_Y00143_Tech011_Cash-005M_P02337.gz](https://github.com/user-attachments/files/16119452/2_Y00143_Tech011_Cash-005M_P02337.gz)

**Comment by dbear496** [comment] 2024-07-08 17:50
Seems there is a bug in the blacksmith code that causes it to occasionally skip the monthly update.

**Comment by dbear496** [comment] 2024-07-08 17:53
Which type of construction did you notice had over 400% production? Usually issues with the production percentage are module-specific.

**Comment by dbear496** [comment] 2024-07-08 17:57
For simple constructions, such as blacksmith, it is expected to have the same production percentage for each commodity. Production percentages between commodities will only differ on more complex modules that have variable efficiency, such as residences.

**Comment by FabioPedretti** [comment] 2024-07-08 18:02
> Which type of construction did you notice had over 400% production?

I don't remember (I didn't suspect it could be a building specific issue).

I should play it again and check (if I have time), I'll let you know if I find it in other buildings.

Maybe it would be possible to add some check (like printing a console warning) in those cases?

**Comment by dbear496** [comment] 2024-07-08 18:40
There is a warning printed to the console but only in debug mode.

**Comment by dbear496** [comment] 2024-07-08 18:44
Is it possible you saw production >~400% in a previous version? I fixed several of those issues in 2.11.0.

**Comment by dbear496** [comment] 2024-07-08 19:05
I assigned this issue as fixed by PR #152, which only addresses the issue with blacksmiths. If you find other constructions with too high production percentage, then please open a new issue.

**Comment by FabioPedretti** [comment] 2024-07-08 19:19
> Is it possible you saw production >~400% in a previous version? I fixed several of those issues in 2.11.0.

No, it was 2.11.0. I played a bit it again and saw 214% still for the blacksmith.

**Comment by dbear496** [comment] 2024-07-08 19:21
> No, it was 2.11.0. I played a bit it again and saw 214% still for the blacksmith.

Was this after checking out #152 and rebuilding?

**Comment by FabioPedretti** [comment] 2024-07-08 19:25
> > No, it was 2.11.0. I played a bit it again and saw 214% still for the blacksmith.
> 
> Was this after checking out #152 and rebuilding?

No, plain 2.11.0, I actually built the bit exact debian package in [my PPA](https://launchpad.net/~oibaf/+archive/ubuntu/test/+packages) and used it.

**Comment by dbear496** [comment] 2024-07-08 19:42
Okay, in that case, you will see the fix in probably 2.11.2. The issue doesn't affect simulation at all, only display, i.e. the blacksmith is not _actually_ pulling 214% production.

**Comment by FabioPedretti** [comment] 2024-07-13 15:10
Coal Mine Deposits can also exceed 100% (plain 2.11.0 version):

![coal](https://github.com/user-attachments/assets/31cc5e70-e8e6-44eb-b666-d3468de054f9)

**Comment by dbear496** [comment] 2024-07-14 13:53
> Coal Mine Deposits can also exceed 100% (plain 2.11.0 version)

This is by design because the deposit percentage is normalized by the amount of starting deposits.

**Closed** 2024-07-15 22:24 UTC
Labels: bug
