### ISSUE TITLE
Bad Times scenario seems to be impossible

### ISSUE THREAD

**Issue by lostwizard** [lincity-ng/lincity-ng#30] opened 2018-02-17 05:16 UTC
The current incarnation of the Bad Times scenario starts over 1 billion in the hole which comes with nearly 800k in interest per year. Has anyone managed to beat it in this incarnation?

**Comment by stikonas** [comment] 2021-05-15 17:54
> The current incarnation of the Bad Times scenario starts over 1 billion in the hole which comes with nearly 800k in interest per year. Has anyone managed to beat it in this incarnation?

It's not impossible. Interest is capped at 1M, so with the correct strategy it is not even that hard.

**Comment by dbear496** [comment] 2024-06-02 19:49
I didn't want to close this issue until I confirmed for myself that it is possible. It took me a few tries, but I eventually got a sustainable economy from the bad times scenario. Furthermore, I gave myself an extra challenge and didn't use ports at any point.

![Screenshot_20240602_151700](https://github.com/lincity-ng/lincity-ng/assets/70439542/ec640f57-48ae-487f-89f3-e29d90f8187f)

Here are some tips for beating the bad times scenario:
- You do not have to have money to have a sustainable economy -- you only need positive income. I found it easier to not even try paying off the debt.
- The interest expense is capped at 1M/year, so take advantage of this.
- Since you cannot build rocket pads without credit, aim for getting a sustainable economy instead of evacuating.
- Since you cannot build recycling centers without credit, it is very difficult to get ore sustainably. I found it easiest to cut ore out of the picture by relying solely on mills for goods production. I once tried using ore mines to get ore, but my city just got full of lakes, and communes do not generate enough ore to be very useful.
- I do not recommend building health centers because the upkeep cost is too high. Instead, layout your city so that pollution does not blow over residences.
- I recommend building basketball courts because they boost your working population so you get more income tax.
- I recommend targeting a population of about 20k so you can get enough income tax to offset the $1M/year interest expense. This is a lot of population to fit in a 100x100 map, so plan your city carefully.
- I recommend using lots of coal because coal tax is sweeeeet. A little hack is to place a coal mine near a lot of communes, so the coal generated by the communes goes into the coal mine. Coal mines have lots of reserve capacity, so it is unlikely you will run out. And this reverse mining does not reset the sustainability counter.
- I do not recommend using renewable energy sources. Besides having high upkeep cost and low efficiency, they also do not use coal. Instead use coal power and again, just layout your city so the pollution does not blow over residences and cause unnatural deaths.
- I recommend bulldozing the entirety of the starting city and all the water. The starting city is very bad, and clearing the map will allow you to layout your city more freely and efficiently. Don't worry too much about the high cost of bulldozing water, because you do not need to pay off the debt to win the game.

**Closed by dbear496** 2024-06-02 19:49 UTC
Labels: gameplay
