### ISSUE TITLE
App crashes immediately after Start button is clicked

### ISSUE THREAD

**Issue by ioogithub** [lincity-ng/lincity-ng#47] opened 2020-12-03 21:28 UTC
This is a new first time install.

1. Install Lincity-NG from KDE Neon Discovery version 2.9git~20150314-3build1
2. Click Start then select Lincity from the launch menu.
3. Game starts, click "New Game"
4. Select any of the maps and click Start
5. Game crashes

I do not see any errors in journalctl, is there another log somewhere that might show what the problem is?

System: KDE Neon version 5.20.3
Graphics: Mesa Intel UHD Graphics 620

**Comment by uafr** [comment] 2020-12-04 00:42
If you start the program from a terminal there might be some helpful output.

**Comment by DanielFaulkner** [comment] 2021-01-03 19:23
I was able to replicate what I suspect is the same issue. With a fresh install (or with the .lincity-ng folder deleted) creating a new game with the River Delta map causes a crash with the error: "carving river ...Floating point exception (core dumped)".

However in my case not all maps were affected, and after opening a non affected map (ie. Beach) subsequent attempts to open the River Delta map worked. Recurring only when the .lincity-ng folder was deleted.

OS: Linux Mint 20 (MATE) - Same Lincity-NG version as the original poster.

**Comment by uafr** [comment] 2021-01-04 14:14
Sounds like #37

**Comment by DanielFaulkner** [comment] 2021-01-04 16:48
@uafr thanks for pointing out that report. I must have overlooked it when looking at the bug tracker. 

I have downloaded and compiled the current source from git master and I can confirm that the floating point error I was referring to in my previous comment appears to be resolved in the master branch and was probably caused by issue #37 .

**Closed** 2021-01-09 14:26 UTC
